-- Session summaries generated by Clara on "Clarify"
create table session_summaries (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references chat_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  contradiction text not null,
  main_keywords text[] not null default '{}',
  personality_insight text not null,
  reframing text not null,
  user_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index idx_session_summaries_session on session_summaries(session_id);
create index idx_session_summaries_user on session_summaries(user_id);

alter table session_summaries enable row level security;

create policy "Users can manage own summaries"
  on session_summaries for all
  using (auth.uid() = user_id);

create trigger session_summaries_updated_at
  before update on session_summaries
  for each row execute function update_updated_at();
